name: Build and Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build (make)
        run: make

      - name: Archive binary
        run: |
          mkdir -p dist
          cp js5 dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          files: dist/js5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
