name: Build and Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build (make)
        run: make

      - name: Préparer le binaire
        run: |
          mkdir -p dist
          strip js5
          cp js5 dist/

      - name: Générer un tag unique
        id: prep
        run: echo "TAG=v$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Créer la release GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release jinsock_${{ env.TAG }}
          files: dist/js5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
